export interface ElectricityDeal {
  id: string
  supplier: string
  price: string
  basePrice: string
  monthlyFee: string
  type: string
  duration: string
  renewable: boolean
  savings: string
  rating: number
  affiliateLink: string
  logo?: string
  showOnFrontpage?: boolean
  // Canonical numeric values (display strings above are derived from these).
  priceValue?: number // snt/kWh
  monthlyFeeValue?: number // €/kk
  savingsValue?: number // €/vuosi
}

// Fallback data used when the live API (Cloudflare D1) cannot be reached.
export const mockDeals: ElectricityDeal[] = [
  {
    id: '1',
    supplier: 'Hehku Energia',
    price: '6,99',
    basePrice: '6,99 snt/kWh',
    monthlyFee: '3,90 €/kk',
    type: 'Kiinteä',
    duration: '12 kk',
    renewable: true,
    savings: '250 €/vuosi',
    priceValue: 6.99,
    monthlyFeeValue: 3.9,
    savingsValue: 250,
    rating: 4.8,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
  {
    id: '2',
    supplier: 'Väre Energia',
    price: '7,15',
    basePrice: '7,15 snt/kWh',
    monthlyFee: '4,20 €/kk',
    type: 'Kiinteä',
    duration: '24 kk',
    renewable: true,
    savings: '220 €/vuosi',
    priceValue: 7.15,
    monthlyFeeValue: 4.2,
    savingsValue: 220,
    rating: 4.7,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
  {
    id: '3',
    supplier: 'Fortum',
    price: '7,45',
    basePrice: '7,45 snt/kWh',
    monthlyFee: '3,50 €/kk',
    type: 'Kiinteä',
    duration: '12 kk',
    renewable: false,
    savings: '200 €/vuosi',
    priceValue: 7.45,
    monthlyFeeValue: 3.5,
    savingsValue: 200,
    rating: 4.5,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
  {
    id: '4',
    supplier: 'Helen',
    price: '7,29',
    basePrice: '7,29 snt/kWh',
    monthlyFee: '4,00 €/kk',
    type: 'Kiinteä',
    duration: '24 kk',
    renewable: true,
    savings: '210 €/vuosi',
    priceValue: 7.29,
    monthlyFeeValue: 4.0,
    savingsValue: 210,
    rating: 4.6,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
  {
    id: '5',
    supplier: 'Oomi',
    price: '6,89',
    basePrice: '6,89 snt/kWh',
    monthlyFee: '3,90 €/kk',
    type: 'Kiinteä',
    duration: '12 kk',
    renewable: true,
    savings: '260 €/vuosi',
    priceValue: 6.89,
    monthlyFeeValue: 3.9,
    savingsValue: 260,
    rating: 4.9,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
  {
    id: '6',
    supplier: 'Caruna Energia',
    price: '7,35',
    basePrice: '7,35 snt/kWh',
    monthlyFee: '4,50 €/kk',
    type: 'Kiinteä',
    duration: '12 kk',
    renewable: false,
    savings: '190 €/vuosi',
    priceValue: 7.35,
    monthlyFeeValue: 4.5,
    savingsValue: 190,
    rating: 4.4,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
  {
    id: '7',
    supplier: 'Lumo Energia',
    price: '7,05',
    basePrice: '7,05 snt/kWh',
    monthlyFee: '3,80 €/kk',
    type: 'Pörssisähkö',
    duration: 'Ei sitoumusta',
    renewable: true,
    savings: '230 €/vuosi',
    priceValue: 7.05,
    monthlyFeeValue: 3.8,
    savingsValue: 230,
    rating: 4.6,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
  {
    id: '8',
    supplier: 'Kotimaan Energia',
    price: '7,19',
    basePrice: '7,19 snt/kWh',
    monthlyFee: '4,00 €/kk',
    type: 'Kiinteä',
    duration: '24 kk',
    renewable: true,
    savings: '215 €/vuosi',
    priceValue: 7.19,
    monthlyFeeValue: 4.0,
    savingsValue: 215,
    rating: 4.5,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
  {
    id: '9',
    supplier: 'Tibber',
    price: '6,95',
    basePrice: '6,95 snt/kWh',
    monthlyFee: '3,90 €/kk',
    type: 'Pörssisähkö',
    duration: 'Ei sitoumusta',
    renewable: true,
    savings: '245 €/vuosi',
    priceValue: 6.95,
    monthlyFeeValue: 3.9,
    savingsValue: 245,
    rating: 4.7,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
  {
    id: '10',
    supplier: 'E.ON',
    price: '7,39',
    basePrice: '7,39 snt/kWh',
    monthlyFee: '4,20 €/kk',
    type: 'Kiinteä',
    duration: '12 kk',
    renewable: false,
    savings: '185 €/vuosi',
    priceValue: 7.39,
    monthlyFeeValue: 4.2,
    savingsValue: 185,
    rating: 4.3,
    affiliateLink: '#',
    showOnFrontpage: true,
  },
]
